include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_null_checks
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_redundant_argument_values
    - prefer_collection_literals
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - avoid_init_to_null
    - prefer_single_quotes
    - require_trailing_commas

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
